spring.application.name=transaction-service
spring.datasource.url=jdbc:postgresql://localhost:5432/transaction_db
spring.datasource.username=dev_user
spring.datasource.password=dev_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false